# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: kiranr
google_analytics: kiranr
title: kiranr.com


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: kiranr
      tagline: a harsh discordant mixture of sounds

description: data and energy beverage connoisseur
author:
  name: Kiran Rajendran
  email: kiran.rajendran@gmail.com
  github: kiranrajendran
  #twitter: 
  #pinterest: 
  linkedin: kiranrajendran
  bio: data and energy beverage connoisseur
  email_md5: c86659a90b8397e8119932de1baa42bd

#rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

plugins:
  - jekyll-paginate
