name: kiranr.com
title: kiranr.com
description: kiranr.com
tags:
  - blog
  - etl
  - pentaho
  - data
  - kettle
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: kiran.rajendran@gmail.com
disqus_username: kiranrajendran
